# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 08:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pointfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointfield',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='gps',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.DeleteModel(
            name='PointField',
        ),
    ]
