# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160524_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='website',
            field=models.CharField(max_length=100),
        ),
    ]
