# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20160525_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
