# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_VoteCom', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='VoteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_VoteLog', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='VoteTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_VoteTech', models.CharField(max_length=500)),
            ],
        ),
    ]
