# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0002_auto_20160526_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='SujetCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SujetVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
            ],
        ),
    ]
