# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0003_sujetcategorie_sujetvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujetvote',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vote_app.SujetCategorie'),
        ),
    ]
