# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0004_sujetvote_categorie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteCom',
        ),
        migrations.DeleteModel(
            name='VoteLog',
        ),
        migrations.DeleteModel(
            name='VoteTech',
        ),
    ]
